### ISSUE TITLE
SimilarityType

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#101]
According to the [SimilarityLookup documentation](http://docs.aws.amazon.com/AWSECommerceService/latest/DG/SimilarityLookup.html) it would be nice to set the **SimilarityType** parameter via SimilarityLookup class as well.

**Comment by Exeu** [comment]
added this via ```@method``` annotation. Your ide should  now offer autocompletion for it.

**Comment by flowdee** [comment]
:+1: thanks @Exeu !
