### ISSUE TITLE
Set MerchantId parameter

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#102]
The MerchantId parameter can be used by multiple operations: ItemSearch, ItemLookup and SimilarityLookup. Would be nice to get a setter for this.

> An optional parameter that can be used to filter search results and offer listings to only include items sold by Amazon. By default, Product Advertising API returns items sold by various merchants including Amazon. Enter "Amazon" **to return only items sold by Amazon**.
> 
> Type: String
> 
> Valid Values: Amazon

**Comment by Exeu** [comment]
added this via ```@method``` annotation. Your ide should  now offer autocompletion for it.

**Comment by flowdee** [comment]
:+1: thanks @Exeu !
