### ISSUE TITLE
PHP 7 SOAPfault: Function ("ItemLookup") is not a valid method for this service

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#103]
Switching to PHP7+ it might happen that the SOAP error from above can be thrown.

After reading the following post: http://www.lornajane.net/posts/2015/soapfault-when-switching-php-versions I solved it with the following two options:

Variant 1:
`ini_set("soap.wsdl_cache_enabled", "0");`

Variant 2:
```
$soapClient = new \SoapClient(
            $this->webserviceWsdl,
            array('exceptions' => 1, 'cache_wsdl' => WSDL_CACHE_NONE)
        );
```

Anyway none of the both variants is the best solution because the caching will be disabled permanently. 

Two options were to empty the wsdl cache folder on the server or moving the cache directory. In my case the users of the application won't be able to do this on their own I guess.

Any ideas for a workaround to solve this inside the apai-io library without disabling the wsdl caching?

**Comment by Exeu** [comment]
Use Rest instead of soap. Currently im thinking of removing SOAP support of this class anyway in version 2.0.

**Comment by flowdee** [comment]
Thanks for your fast reply @Exeu. Switching over to REST is fine for me. Additionally thanks for the note about the soap support drop.

**Comment by BenMorel** [comment]
Note: just clearing the WDSL cache worked for me after switching to PHP 7.
