### ISSUE TITLE
GuzzleRequest not Found

### ISSUE THREAD

**Issue by ishaanfinomena** [Exeu/apai-io#114]
PHP Fatal error:  Class 'ApaiIO\Request\GuzzleRequest' not found in /home/forge/apai-io-master/test.php on line 13

<?php
require_once "vendor/autoload.php";
use ApaiIO\Configuration\GenericConfiguration;
use ApaiIO\Operations\Search;
use ApaiIO\ApaiIO;
class c1
{
        public static function a()
        {
                echo "Hello<br>";
                $client = new \GuzzleHttp\Client();
                $request = new \ApaiIO\Request\GuzzleRequest($client);

                $conf = new GenericConfiguration();
                $conf
                        ->setCountry('in')
                        ->setAccessKey('A******************Q')
                        ->setSecretKey('****************************************')
                        ->setAssociateTag('***************')
                        ->setRequest($request);
                $apaiIO = new ApaiIO($conf);

                $search = new Search();
                $search->setCategory('DVD');
                $search->setActor('Bruce Willis');
                $search->setKeywords('Die Hard');
                $formattedResponse = $apaiIO->runOperation($search);

                echo var_dump($formattedResponse);
        }
}
?>

**Comment by Exeu** [comment]
sry the testscript looks so weird. please check if your autoloader works correctly.

**Comment by Exeu** [comment]
You should NOT edit the checkout of APAIIO itself... Go ahead -> Create a blank empty project. create a composer.json file and add the content of what is in this README.md and run a composer install.

**Comment by alibaig4u** [comment]
can u give me the structure of folder, where to install exeu/apai-io please. i am not understanding which file i have to run

**Comment by alibaig4u** [comment]
and when i am adding the request line to the composer.json, after adding these i am running the installation then it occured a msg
  Problem 1
    - The requested package exeu/apai-io No version set (parsed as 1.0.0) is sat
isfiable by exeu/apai-io[No version set (parsed as 1.0.0)] but these conflict wi
th your requirements or minimum-stability.
i dont why why :(

**Comment by alibaig4u** [comment]
![image](https://cloud.githubusercontent.com/assets/14124603/15821268/390733f2-2c08-11e6-9d51-0abc675caf5e.png)
these are my folder files

**Comment by alibaig4u** [comment]
its my index.php file
![image](https://cloud.githubusercontent.com/assets/14124603/15821286/56cd9af2-2c08-11e6-8ff5-8c67cafe7720.png)

**Comment by Exeu** [comment]
if you have a look in your folder you'll see that there is NO apaio inside of the vendor folder....
please again read at least the README file how to use this.

I will summarize that a bit for you:

Create an empty folder.
Go into this folder.
create a file named composer.json
open this composer.json
copy and paste the content (you see this content in the README) to this file.
run composer install afterwards

**Comment by alibaig4u** [comment]
ok let me try. thanks by the away :)
