### ISSUE TITLE
When i try the Samples it says to set up the project dependencies 

### ISSUE THREAD

**Issue by bar2016** [Exeu/apai-io#118]
Hi i am trying to use the Sample and its says
You must set up the project dependencies, run the following commands: curl -s http://getcomposer.org/installer | php php composer.phar install
what should i do?

**Comment by liadrianlozano** [comment]
Basically what composer does is to gather and download all libraries a project needs to work, this is called "dependencies". Sadly there is never instructions for this, as developers asume other developers know about this. 

You need to install the composer, if you are under windows. you should go to this site:
http://getcomposer.org/installer

And then download and install composer.
Then, follow instructions on how to run composer over the files of the project.

Usually you go to command prompt and locate your project folder, then run the command:

> composer install
