### ISSUE TITLE
Help Exeu

### ISSUE THREAD

**Issue by jonathanquehay** [Exeu/apai-io#120]
Hello Exeu, can do some step by step process of using the library apai-io I have two days to try to make you run and I have not accomplished.

**Comment by jonathanquehay** [comment]
![image](https://cloud.githubusercontent.com/assets/4674114/17863680/e511476a-6857-11e6-9d90-730f4ef0119b.png)

**Comment by jonathanquehay** [comment]
this error, idont now

**Comment by bar2016** [comment]
@jonathanquehay Same here, Damm

**Comment by bar2016** [comment]
@jonathanquehay i think its a bad resposne checj this out
this if -
if (!$response) {
..
..
..
return new $className($message, $request, $response, $previous, $ctx);-Line 107 and here is the problem

**Comment by bar2016** [comment]
@jonathanquehay Hi, i solved it , i found that i haven't complete fully the registeration so check this out this error apear with like wrong Keys or unvalid you have check in google Amazon Scratch pad 
http://webservices.amazon.com/scratchpad/index.html
