### ISSUE TITLE
Retrieve items by browse node

### ISSUE THREAD

**Issue by wjgilmore** [Exeu/apai-io#125]
Hi,

Thank you for the great library. I'm able to search using keywords, however I can't seem to retrieve any results when searching by browse node:

        $search = new Search();
        $search->setBrowseNode(156128011);
        $search->setResponseGroup(['Medium']);

Why is this? I receive an XML-formatted response, however the `Items` node looks like this:

    <Items>
      <Request>
        <IsValid>True</IsValid>
        <ItemSearchRequest>
          <BrowseNode>156128011</BrowseNode>
          <ResponseGroup>Medium</ResponseGroup>
        </ItemSearchRequest>
      </Request>
    </Items>

Any idea why this isn't populated with books in a fashion similar to that when searching using a keyword?

Thank you,
Jason

**Comment by Exeu** [comment]
As this now is amazon related you should have a look at the documentation of amazon for that reason.
maybe this node does not exist in the country. or wrong id.
