### ISSUE TITLE
idType

### ISSUE THREAD

**Issue by gelinger777** [Exeu/apai-io#128]
Am I missing in documentation something? How to set idType ? 

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/OtherItemIdentifiers.html  

??? 
I have made a pull request of code which I did. but seems its incomplete.

**Comment by Exeu** [comment]
.... 

According to the Documentation of Amazon there is NO IdType for Search.
It should be ItemLookup....

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemLookup.html

Use the ItemLookup class for this kind of search. 

$lookup->setIdType("EAN");

**Comment by gelinger777** [comment]
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/EX_LookupbyISBN.html  What you would say to this one? There is a param idType in search.

**Comment by Exeu** [comment]
Again: This is not Search -> This is Lookup.
