### ISSUE TITLE
amazon.nl is missing

### ISSUE THREAD

**Issue by mp31415** [Exeu/apai-io#135]
CountryList in Country.php needs an extra entry for Netherlands: 'nl'.
Thanks.

**Comment by JanKrohn-Khalibre** [comment]
Amazon.nl has no API access yet. :-(

**Comment by mp31415** [comment]
Oh, thank you, did not even think about that possibility.

**Comment by JanKrohn-Khalibre** [comment]
I've also been waiting for it for a long time...
