### ISSUE TITLE
Break changes v1 vs v2?

### ISSUE THREAD

**Issue by pensiero** [Exeu/apai-io#142]
Hi, are there any break changes between v1 and v2?

Thanks

**Comment by Exeu** [comment]
- RequestFactories are gone
- ResponseTransformerFactories are gone
- SOAP support dropped
- Guzzle as abstraction-layer was introduced.

https://github.com/Exeu/apai-io/compare/1.10.0...2.0.0

**Comment by pensiero** [comment]
Thank you
