### ISSUE TITLE
curl multi handle?

### ISSUE THREAD

**Issue by cschalenborgh** [Exeu/apai-io#143]
Are there any plans to integrate curl multi handle for asynchronously requests?

Thanks

**Comment by Exeu** [comment]
This feature is not planned. 

**If you want to use this to make more request at the same time:**
Maybe you are better served with a batch request.

Note that Amazon anyway has request throtteling in place.
So for the most users the request limit is anyway at 1 request per second.

http://docs.aws.amazon.com/AWSECommerceService/latest/DG/TroubleshootingApplications.html#efficiency-guidelines
