### ISSUE TITLE
Product Advertising API Amazon

### ISSUE THREAD

**Issue by vovanduc** [Exeu/apai-io#144]
**Hi,**

My name is Duc, my job is developer website. I need a Product Advertising API Associate account, but I can not register because I do not have an online shop. I just need it to get the products of amazon. You can sell or share account Associate ?

Sorry for my English is not good

**Thanks!**

**Comment by k0d3rR** [comment]
@vovanduc Register a free wordpress blog at www.wordpress.com and then use that information to register

**Comment by Exeu** [comment]
No account  selling.
