### ISSUE TITLE
Missing option: Request timeout

### ISSUE THREAD

**Issue by andreisusanu** [Exeu/apai-io#147]
Hello,

Is it possible to add a request timeout? Some of my calls are taking forever...

http://docs.guzzlephp.org/en/latest/request-options.html#timeout

Thanks!

**Comment by Exeu** [comment]
Have a look at the guzzle documentation:

http://docs.guzzlephp.org/en/latest/quickstart.html#creating-a-client

There you see:
`
$client = new Client([
    // ...
    // You can set any number of default request options.
    'timeout'  => 2.0,
]);
`

As apiio uses a client object which you have to inject you can use a client with a timeout setting.

**Comment by andreisusanu** [comment]
Indeed... sorry for the dumb question. Cheers!
