### ISSUE TITLE
Limit 10 pages (100 results) - Alternatives

### ISSUE THREAD

**Issue by fjhadz1** [Exeu/apai-io#149]
Hi, I'm planning to build my own rank tracker and I'm aware that the amazon product advertising api only limit 10 pages (100 results). 
I appreciate any insights/Idea on how to achieve in creating my own amazon rank tracker (or getting 100+results)? In addition to that, any logic how amztracker/amzshark achieve it?.

**Comment by obayesshelton** [comment]
using the min and max pricing

**Comment by odonel195** [comment]
How would you use min and max pricing obayesshelton? dying to know

**Comment by obayesshelton** [comment]
Well, you could do something like the following:

```
$search = new Search();
$search->setCategory($category);
$search->setKeywords($keywords);
$search->setPage($pageCount);
$search->setResponseGroup(['Small', 'Large']);
$search->setMinimumPrice($startPrice);
$search->setMaximumPrice($startPrice);
$formattedResponse = $this->apaiIO->runOperation($search);
```
and start off with the min price set as $0.01 and max as $0.02, then go through your 1 to 10 pages then at the end of the 10 pages increment the min and max by 1 cent. This way you can get far more products. 

I am currently doing this in multiple production sites.

**Comment by odonel195** [comment]
Thank you for your help abayesshelton. Were you able to get the apaiIO to work ? Even from github the demo did not work for me.

**Comment by obayesshelton** [comment]
well, it's not very complicated, without seeing your code I cannot comment.

**Comment by odonel195** [comment]
forgive me obayyesshelton, i am new at this. I thought it was some  sort of a web app that I could copy and run. I just installed composer yesterday and looking at a few tutorials to get this going. My main objective is to search the API by min/max price and returns other info such as rank/avg rank, asin/isbn and on. If you know a quicker way for me achieve my goal, please share. Thank you

**Comment by obayesshelton** [comment]
no, this is a pretty good start.

**Comment by dingman** [comment]
Amazon's docs say that after you're generating X dollars in sales per month, you can request an increase to the number of results per API call.
