### ISSUE TITLE
AWS.Invalid (truncated...)

### ISSUE THREAD

**Issue by balachandermca2012** [Exeu/apai-io#157]
Hi i am getting an error on item search api. can you guide me how to resolve the below issue.

GET http://webservices.amazon.in/onca/xml?AWSAccessKeyId=XXX--XXXX--XX&AssociateTag=$$$$-$$&ItemId=B00KGZZ824&Operation=ItemLookup&ResponseGroup=Large%2CSmall&Service=AWSECommerceService&Timestamp=2017-07-20T19%3A30%3A17Z&Version=2013-08-01&Signature=dkAxHRk3cPJ9XCaJXW7WlN5k1Vfb6eYl0AnF3SsViMo%3D` resulted in a `400 Bad Request` response:
<?xml version="1.0"?>
<ItemLookupErrorResponse xmlns="http://ecs.amazonaws.com/doc/2013-08-01/"><Error><Code>AWS.Invalid (truncated...)

Thanks
Bala

**Comment by PendalF89** [comment]
Same problem. Are you solved it?

**Comment by PendalF89** [comment]
I solve it!
See: http://webservices.amazon.com/scratchpad/index.html
You need connect API key to Affiliate API

**Comment by balachandermca2012** [comment]
Hi Pendal, 
   How to connect API key to Affiliate api. still now am getting same error

**Comment by PendalF89** [comment]
I don't remember steps exactly, but you can try API via scratchpad and if not working, scratchpad tell you how to connect API key.

**Comment by balachandermca2012** [comment]
Thanks, Pendal, issue fixed
need to signup below url. and automatically connected  API key to Affiliate API
https://affiliate-program.amazon.in/gp/advertising/api/detail/main.html
