### ISSUE TITLE
Search for ASIN

### ISSUE THREAD

**Issue by israel78** [Exeu/apai-io#160]
Hello,
How can I perform a search for ASIN? Try the following:

$search = new Search();
$search->setCategory('All');
$search->setResponsegroup(array('Large', 'Images'));
$search->setItemId('B013UDL5RU');
$apaiIo = new ApaiIO($conf);
$response = $apaiIo->runOperation($search);

But it does not return results.
Any solution?
Thank you

**Comment by israel78** [comment]
solucionado con Lookup!!

**Comment by dingman** [comment]
Have you tried the scratchpad to make sure the API is returning results for that particular product?

http://webservices.amazon.com/scratchpad/index.html

**Comment by gerardnll** [comment]
Just in case people does not know and stumble across this issue, here's the way to lookup product by ASIN:

```
$conf = new GenericConfiguration();
$client = new Client();
$request = new GuzzleRequest($client);

$conf->setCountry('es') // or com, co.uk, .....
      ->setResponseTransformer(new XmlToSimpleXmlObjectTransformer()) // Optional
      ->setAccessKey('xxxxxxx') // your access key from aws
      ->setSecretKey('xxxxxx') // your secret key from aws
      ->setAssociateTag('xxxxxxxx') // if you have an affiliate id
      ->setRequest($request);
$apaiio = new ApaiIO($conf); // use ApaiIO\ApaiIO;

$itemLookup = new Lookup(); // use ApaiIO\Operations\Lookup;
$itemLookup->setItemId('B013UDL5RU');
$itemLookup->setResponseGroup(['ItemAttributes', 'Images', 'OfferSummary']); // whatever information you want to receive

$apaiio->runOperation($itemLookup);
```

I suggest mantainers to close this issue.
