### ISSUE TITLE
how to use without composer?

### ISSUE THREAD

**Issue by abioneperhobby** [Exeu/apai-io#166]
hi,
i need to store and use your library in a website on witch i cannot install composer, because is a wordpress shared hosting, so i have php, but i don't have any other kind of access.

can someone please provide a solution?

i tried installing the library with composer locally and then move all the folder "vendor" in the shared space, but when i try to open a /sample file, for example this vendor/exeu/apai-io/samples/Lookup/SimpleLookup.php , i obtain
You must set up the project dependencies, run the following commands: curl -s http://getcomposer.org/installer | php php composer.phar install

thanks.

**Comment by dana321** [comment]
Did you also copy the composer.json and composer.lock files to the same level as the vendor folder? All the files are required for composer to function. You then just include the vendor/autoload.php file.
