### ISSUE TITLE
GuzzleHttp\Exception\ServerException

### ISSUE THREAD

**Issue by ibrahim4145** [Exeu/apai-io#167]
I believe i am getting this error because i am crossing limit of hits per hour if anybody know exactly how many request we can hit per hour please let me know 

Here is the error i am getting on browseNodeLookup API
![image](https://user-images.githubusercontent.com/8254586/34513645-10020fe2-f08b-11e7-9eb4-9c243619cc36.png)

**Comment by attheshow** [comment]
Same.

**Comment by attheshow** [comment]
It looks like we need to add this into GuzzleRequest.php

`use GuzzleHttp\Exception\RequestException;`
