### ISSUE TITLE
safe_mode & open_basedir issue

### ISSUE THREAD

**Issue by scott-davidjones** [Exeu/apai-io#34]
Hi I have a client, that I implemented this for, that used shared hosting, when using this library I am getting the following errors:
 Fatal error: Uncaught exception 'RuntimeException' with message 'An error occurred while setting 52 with value 1' in {omitted}/vendor/exeu/apai-io/lib/ApaiIO/Request/Rest/Request.php:143

i took a look at that file and the following code is there:

``` php
foreach ($options as $currentOption => $currentOptionValue) {
            if (false === @curl_setopt($ch, $currentOption, $currentOptionValue)) {
                throw new \RuntimeException(
                    sprintf(
                        "An error occurred while setting %s with value %s",
                        $currentOption,
                        $currentOptionValue
                    )
                );
            }
        }
```

after removing the @ and running again i see the following error:
Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when safe_mode is enabled or an open_basedir is set in {omitted}/vendor/exeu/apai-io/lib/ApaiIO/Request/Rest/Request.php on line 142

would there be a way to get round this?

**Comment by flowdee** [comment]
I've got a client with the same problem. In my case I already added the FOLLOW_LOCATION 0:

`$conf = new GenericConfiguration();

            $x = new \ApaiIO\Request\Rest\Request(array(\ApaiIO\Request\Rest\Request::FOLLOW_LOCATION => 0));

            try {
                $conf
                    ->setCountry($country)
                    ->setAccessKey($aws_api_key)
                    ->setSecretKey($aws_api_secret_key)
                    ->setAssociateTag($aws_associate_tag)
                    //->setRequest('\ApaiIO\Request\Rest\Request')
                    //->setResponseTransformer('\ApaiIO\ResponseTransformer\XmlToDomDocument');
                    //->setRequest('\ApaiIO\Request\Soap\Request')
                    //->setResponseTransformer('\ApaiIO\ResponseTransformer\ObjectToArray');
                    ->setRequest($x);
            } catch (\Exception $e) {
                echo $e->getMessage();
            }

            $amazon = new ApaiIO($conf);`

but nethertheless his shared hosting returns the error:

`PHP Warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in /var/www/vhosts/.../libs/apai-io/exeu/apai-io/lib/ApaiIO/Request/Rest/Request.php on line 146`

I followed the installation steps and my configuration is attached above. Any idea what it could be @Exeu  ?

**Comment by flowdee** [comment]
In addition to my previous post, I tested a little bit around and found something interesting:

    public function __construct(array $options = array())
    {
        $this->options = array(
            self::USERAGENT          => "ApaiIO [" . ApaiIO::VERSION . "]",
            self::CONNECTION_TIMEOUT => 10,
            self::TIMEOUT            => 10,
            self::FOLLOW_LOCATION    => 0
        );
        $this->setOptions($options);
    }

After setting the FOLLOW_LOCATION to 0 inside the constructor, the problem disappeared. Shouldn't be this setting be overwritten by the following line?

`$x = new \ApaiIO\Request\Rest\Request(array(\ApaiIO\Request\Rest\Request::FOLLOW_LOCATION => 0));`

**Comment by Exeu** [comment]
Yes it will ;) see setOptions function.

**Comment by flowdee** [comment]
Yeah but why does the error still occur? As I wrote **CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set** only disappears when I edit the _Rest/Request.php_ constructor manually.

**Comment by Exeu** [comment]
Go ahead and grab a debugger. Step into it and investigate what is happening there in your case.
More i cannot do for you.
