### ISSUE TITLE
Response impossible to treat

### ISSUE THREAD

**Issue by toumz** [Exeu/apai-io#48]
$response = $apaiIo->runOperation($search) returns a long string depending on the response group chosen. It is impossible for me to convert it to the XML form described in amazon documentation. Is there something that I forgot or do I need to parse this string ?

Thank you for this incredible work !

**Comment by jonathanquehay** [comment]
Hello Exeu, can do some step by step process of using the library apai-io I have two days to try to make you run and I have not accomplished.
