### ISSUE TITLE
Advantage of Installing in the Way You Recommend?

### ISSUE THREAD

**Issue by ChayimZaklad** [Exeu/apai-io#52]
I've gotten your sample code to work without installing your library in your recommended fashion.  I just included all the libary files, in required order, in my PHP code, and I commented out the require_once of bootstrap.php.  This avoided dealing with shared server management to get them to install the way you recommend.

What advantages would I have if I get it installed the way you recommend instead?  And, what disadvantages do I have doing it the way I have?

**Comment by Bhabatosh** [comment]
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package exeu/apai-io 1.0.0 could not be found.
  Problem 2
    - Installation request for exeu/apai-io dev-master -> satisfiable by exeu/apai-io[dev-master].
    - exeu/apai-io dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

my composer.json file content as follows: 
{
    "name": "exeu/apai-io",
    "type": "library",
    "description": "Amazon Product Advertising PHP Library",
    "keywords": ["Amazon", "ECS", "Product Advertising", "SOAP", "REST", "Products"],
    "homepage": "https://github.com/Exeu/apai-io",
    "license": "Apache-2.0",
    "authors": [
        {
            "name": "Jan Eichhorn",
            "email": "exeu65@googlemail.com",
            "role": "Maintainer"
        },
        {
            "name": "Dejan Spasic",
            "email": "dejan.spasic@bitweise.biz",
            "role": "Developer"
        }
    ],
    "support": {
        "issues": "https://github.com/Exeu/apai-io/issues"
    },
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.3.0",
        "ext-curl": "*"
    },
    "require": {
        "exeu/apai-io": "dev-master"
    },
    "autoload": {
        "psr-0": { "ApaiIO": "lib/" }
    }
}
