### ISSUE TITLE
Help to format proper request for gettings items in a node.

### ISSUE THREAD

**Issue by Niteblade** [Exeu/apai-io#62]
To anyone who can help:

I have one issue in two parts.

Part I.
Will someone help me determine how I can I get a list of items (... the first 10 results would be fine ...) from a node when I provide the node number? The short story is that Amazon does not provide RSS feeds for some of its nodes ... for example node 3445246011. However, even though there is not an RSS feed for this node, there are still products available. http://www.amazon.com/l/3445246011

```php
use ApaiIO\ApaiIO;
use ApaiIO\Configuration\GenericConfiguration;
use ApaiIO\Operations\Search;

$conf = new GenericConfiguration();

try {
    $conf
        ->setCountry('com')
        ->setAccessKey('***')
        ->setSecretKey('***')
		->setRequest('\ApaiIO\Request\Rest\Request')
        ->setAssociateTag('***');
		
} catch (\Exception $e) {
    echo $e->getMessage();
}
$apaiIO = new ApaiIO($conf);

$search = new Search();
$search->setBrowseNode(3445246011);
$search->setResponseGroup(array('Medium'));
$response = $apaiIO->runOperation($search);
$response = json_decode (json_encode (simplexml_load_string ($response)), true);

echo '<pre>';
print_r ($response);
echo '</pre>';
```

Part II.
In a perfect world, I would have apai-io create a properly formatted request and then I would use another piece of software -- [Zebra_cURL](http://stefangabos.ro/php-libraries/zebra-curl/) -- to grab the properly formatted feed and cache the response from that feed locally. In this manner, I would avoid hammering the Amazon API. However, I don't think it's possible to view the properly formatted feed that apai-io creates -- or is it?

Thanks!

**Comment by Exeu** [comment]
For this cases you mention the library provides two interfaces which can be used.

First of all have a look on the documentation:
http://exeu.github.io/apai-io/the-responsetransformer.html

Maybe there you have an hint for HOW to format a list of results or even sort it in the way you need.

For Part 2:
The interface https://github.com/Exeu/apai-io/blob/master/lib/ApaiIO/Request/RequestInterface.php is maybe that what you are looking for (i dont get your intention completely).
Implement that Interface in a new class which handles the caching. And when the cache fails -> you can execute the real request to amazon.

```php
$restRequest = new RestRequest();
$requestCacheProxy = new MyAwesomeCacheClass($restRequest);

$conf->setRequest($requestCacheProxy);
```
