### ISSUE TITLE
You are submitting requests too quickly. Please retry your requests at a slower rate

### ISSUE THREAD

**Issue by mfrosch** [Exeu/apai-io#65]
Hi Exeu,

I'm currently testing your library and it's working well, so - thanks.

But sometimes I receive the error "requests too quickly". I know this error comes from amazon but I have in mind, that there was somewere an option to slow this down by your lib. But I can't find it anymore.

Can you give me a hint?

Thanks and cheers,
Matthias

**Comment by Daijobou** [comment]
Amazon allow only request 10 items per second. So I use loop +10 with http://php.net/manual/en/function.sleep.php

**Comment by mfrosch** [comment]
Looks like my privious respond was not fully submitted.
Thanks for your anwser - also doing it now with sleep.

Cheers

**Comment by Exeu** [comment]
Hi,

no there is nothing implemented in this library.
Maybe you used the old one before which has a very rudimentary sleep hack to avoid this:

https://github.com/Exeu/Amazon-ECS-PHP-Library/blob/master/lib/AmazonECS.class.php#L225

Cheers

**Comment by mohislm** [comment]
Having the throttling support built into the library could save a lot of pain and blood. Currently I'm trying to achieve this with a smart sleep technique. The request is initially followed by a 1 sec sleep(). If still blocked by the API server, try 2 sec, and then 4 sec... 8 sec... and so on. Unfortunately I have seen multiple times when the program has slept up to 2048 seconds (34 minutes) and still no resolution - requests keep on getting blocked. Does anyone have any clue on this? Or their API server is just outsmarting my technique?

**Comment by napolux** [comment]
Have you tried a different IP? Maybe yours is under heavy throttling for past "abuse"...

**Comment by daFish** [comment]
@mohislm Have you inspected the response? Maybe some more information is sent back with the headers.

**Comment by mohislm** [comment]
@napolux I'm on a brand new IP on a cloud-based server. Recently I just made an update so that every request is being sent followed by a 1 sec delay. Before I was just pausing only if it was throttled. This improved the performance a lot. But still getting intermittent blockages every now and then.

**Comment by amphee** [comment]
Hello
I have also same error.
Please give me solution.

Thanks

**Comment by arkste** [comment]
something like this should work:

```php
search:
$search = new Search();
try {
    $response = $this->apaiio->runOperation($search);
} catch (\SoapFault $e) {
    if (strstr($e->getMessage(), 'submitting requests too quickly')) {
        sleep(10);
        goto search;
    }
    continue;
}
```
