### ISSUE TITLE
No results returned

### ISSUE THREAD

**Issue by 3zzy** [Exeu/apai-io#66]
Hi,

Thanks for developing this library. I'm trying to search an item and although amazon search reveals results, but the API doesn't.

    $search = new Search();
    $search->setResponseGroup(array('ItemAttributes','ItemIds','Large'));
    //$search->setCategory('All');
    $search->setBrand('STARTECH'); 
    $search->setKeywords('HDMI to VGA Adapter Converter 1920x1080');
    $search->setCondition('New');
    $search->setMinimumPrice('36.982'); 

.... there're no errors either so the query is correct. But as you can see here: http://www.amazon.com/s/ref=sr_nr_p_89_0?fst=as%3Aoff&rh=i%3Aaps%2Ck%3AHDMI+to+VGA+Adapter+Converter+1920x1080%2Cp_89%3AStarTech&keywords=HDMI+to+VGA+Adapter+Converter+1920x1080&ie=UTF8&qid=1424846004&rnid=2528832011 it should return results.

Setting category to all and remove brand shows results though. I tried the case sensitive brand name also, but still no results.

**Comment by cyrrill** [comment]
All prices in the Amazon API need to be integers, representing cents.

Try again with  3698, instead of 36.982,  and see if it works.

**Comment by 3zzy** [comment]
Ohk, tried `bcmul($price, 100)` but still no results. Also weird that it doesn't let me set MinPrice with `All` (`When SearchIndex equals All, MinimumPrice cannot be present`)

**Comment by cyrrill** [comment]
Hard to tell without running it locally to debug. Try the query here:
https://associates-amazon.s3.amazonaws.com/scratchpad/index.html
You can add additional parameters in the "Request" tab.
If you can't get results as expected here either, it's an Amazon issue rather than the API library.

**Comment by soltrinox** [comment]
setBrand is not defined?

**Comment by cyrrill** [comment]
It's not defined in the Search class per se, but if you look at the parent from which it extends from, AbstractOperation: you will see that it implements the functionality using the PHP magic __call() method:

https://github.com/Exeu/apai-io/blob/master/lib/ApaiIO/Operations/AbstractOperation.php#L57
https://secure.php.net/manual/en/language.oop5.overloading.php#object.call
