### ISSUE TITLE
SSL connection required for SOAP authentication

### ISSUE THREAD

**Issue by sisodiakaran** [Exeu/apai-io#68]
All was working fine, but suddenly Error "SSL connection required for SOAP authentication" arises.  Is this some thing wrong with Amazon API Servers or I am missing something in client configuration?

**Comment by sisodiakaran** [comment]
any clue?

Thanks in advance.

**Comment by daFish** [comment]
Do you have OpenSSL support builtin your PHP?

**Comment by sisodiakaran** [comment]
Yes, I have OpenSSL. As I mentioned it was working all fine, so I think code and server configuration is fine.
