### ISSUE TITLE
Error getting data with SOAP

### ISSUE THREAD

**Issue by sandrovix** [Exeu/apai-io#70]
Hello. First of all, thank you for the great library.
I was successfully returning products for almost 6 months with no issues. Without changing any line of code, the PHP code stop working few days ago, see error message. Before the error message, I am putting pieces of my code. Thank you in advance.

    	->setResponseTransformer('\ApaiIO\ResponseTransformer\ObjectToArray')
    	->setRequest('\ApaiIO\Request\Soap\Request')
        ->setCountry('com')

	$browseNodeLookup = new BrowseNodeLookup();
	$browseNodeLookup->setNodeId('2619526011'); /*node number */
	$browseNodeLookup->setResponseGroup(array('TopSellers', 'MostWishedFor'));
	$formattedResponse = $apaiIO->runOperation($browseNodeLookup); 

	if (array_key_exists("TopItemSet", $formattedResponse["BrowseNodes"]["BrowseNode"]))

The error is happening exactly in the last line above. The error message is below. 

Fatal error: Uncaught SoapFault exception: [aws:Server.InternalError] We encountered an internal error. Please try again. in /home/storage/e/3d/de/site157/public_html/backend/data_reader/lib/ApaiIO/Request/Soap/Request.php:152 Stack trace: #0 /home/storage/e/3d/de/site157/public_html/backend/data_reader/lib/ApaiIO/Request/Soap/Request.php(152): SoapClient->__soapCall('BrowseNodeLooku...', Array) #1 /home/storage/e/3d/de/site157/public_html/backend/data_reader/lib/ApaiIO/Request/Soap/Request.php(67): ApaiIO\Request\Soap\Request->performSoapRequest(Object(ApaiIO\Operations\BrowseNodeLookup), Array) #2 /home/storage/e/3d/de/site157/public_html/backend/data_reader/lib/ApaiIO/ApaiIO.php(73): ApaiIO\Request\Soap\Request->perform(Object(ApaiIO\Operations\BrowseNodeLookup)) #3 /home/storage/e/3d/de/site157/public_html/backend/data_reader/reader_part_1.php(65): ApaiIO\ApaiIO->runOperation(Object(ApaiIO\Operations\BrowseNodeLookup)) #4 {main} thrown in /home/storage/e/3d/de/site157/public_html/backend/data_reader/lib/ApaiIO/Request/Soap/Request.php on line 152

**Comment by Exeu** [comment]
I copied your lines of code and executed the operation. It works. Can you recheck?

Sometimes the API from amazon produces errors. This always could be the case.

Otherwise you can try to use the Restrequest instead of soap.
