### ISSUE TITLE
html entities are not correct

### ISSUE THREAD

**Issue by dazzlingflash** [Exeu/apai-io#72]
No matter which Transformer I use, my output is always somthing like:

http://www.amazon.de/Stirb-langsam-Ein-guter-Sterben/dp/B00HX0HCC4%3FSubscriptionId%3DAKIAISBSCO24IFLAVO6Q%26tag%3Dmytag-21%26linkCode%3Dsp1%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB00HX0HCC4

So there is %3D instead of an equal sign. Is there a way to fix it?

**Comment by Exeu** [comment]
What about: urldecode()?

http://php.net/manual/de/function.urldecode.php

**Comment by dazzlingflash** [comment]
Yeah. I used this. It's just the same on the demo site: http://apaiio.dev.pixel-web.org/
The Amazon Link Checker return false. So it might be useful to use urldecode() in the lib.
However, thanks for your awesome work.
