### ISSUE TITLE
It is possible to get more than 10 pages of results?

### ISSUE THREAD

**Issue by naifamoodi** [Exeu/apai-io#75]
Looks like I can only go through 10 pages. Is it possible to get say 10 items from the 15th page?

**Comment by Exeu** [comment]
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/ItemSearch.html 

Look for: ItemPage

**Comment by naifamoodi** [comment]
Unfortunately ItemPage can only take you up to the 10th page :(
