### ISSUE TITLE
Problem with ResponseTransformers

### ISSUE THREAD

**Issue by pepebe** [Exeu/apai-io#77]
Perhaps I got the syntax wrong, but every ResponseTransformer returns "empty"

```
<?php
/**/

    require_once "{omitted}/vendor/autoload.php";

    use \ApaiIO\Configuration\GenericConfiguration;
    use \ApaiIO\Operations\Search;
    use \ApaiIO\ApaiIO;
    use \ApaiIO\ResponseTransformer\ObjectToArray;

    $ObjectToArray = new ObjectToArray();
    
    $x = new \ApaiIO\Request\Rest\Request(
        array(
            \ApaiIO\Request\Rest\Request::FOLLOW_LOCATION => 0
        )
    );
    
    $conf = new GenericConfiguration($x);
    
    try 
    {
        $conf
        ->setCountry('de')
        ->setAccessKey($modx->getOption('amazon.access.key.id'))
        ->setSecretKey($modx->getOption('amazon.secret.access.key'))
        ->setAssociateTag($modx->getOption('amazon.associate.tag'))
        ->setRequest($x);
        
        if(isset($ObjectToArray)){
            $conf->setResponseTransformer($ObjectToArray);
        }
    } 
    catch (\Exception $e) 
    {
        return $e->getMessage();
    }

    $apaiIo = new ApaiIO($conf);

    
    /* Start: Search */
    $search = new Search();
    $search->setCategory('Books');
    $search->setAuthor('Steve Jackson');
    $search->setKeywords('Fighting Fantasy');
    $search->setCondition('Used');  
    /* End: Search */
    
    $response = $apaiIo->runOperation($search);
    
    var_dump($response);
    
    // return $response;
```

Without ResponseTransformer I get a nice string:

> string(18023) "...."

The string includes all the stuff I expect.

But if I want to use a Response Transformer (for example: ObjectToArray) I get this result:

> array(0) { } 

In my error log I find this message: 

> [2015-04-24 14:48:59] (ERROR @ {omitted}/vendor/exeu/apai-io/lib/ApaiIO/ResponseTransformer/ObjectToArray.php : 45) PHP warning: Invalid argument supplied for foreach()

It seems foreach() inside buildArray($object) doesn't get a valid object.

Any idea whats going on here?

pepebe

**Comment by pepebe** [comment]
This is a bit embarrassing...

> The ObjectToArray ResponseTransformer transforms Objects (stdClass) to an array. Its basicly used when you decided to make SOAP requests.

This won't work with REST, but it works beautifully with SOAP request.

Case closed.

**Comment by mrfuad2007** [comment]
Dear pepebe,
please tell me how to do the SOAP Request to overcome this problem?
