### ISSUE TITLE
Amazon sidebar filters -> how to retrieve?

### ISSUE THREAD

**Issue by cschalenborgh** [Exeu/apai-io#81]
Does anyone have any ideas/suggestions on how to retrieve the product property filters? I'd like to have similar filters as Amazon has in their sidebar: http://www.amazon.com/s/ref=s9_acss_bw_ct_refTest_ct1_a1?ie=UTF8&page=1&rh=n:172659,p_n_feature_keywords_three_browse-bin:7688788011,n:!493964,n:1266092011,n:172282&pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-2&pf_rd_r=1MBJXCS6SY99SM7HMSX9&pf_rd_t=101&pf_rd_p=2090524742&pf_rd_i=172659

![screen shot 2015-05-20 at 16 29 48](https://cloud.githubusercontent.com/assets/10864861/7728118/94279714-ff0d-11e4-8b37-2952f3759c6d.png)
![screen shot 2015-05-20 at 16 29 55](https://cloud.githubusercontent.com/assets/10864861/7728117/94263aa4-ff0d-11e4-830e-779c2a35cf24.png)

**Comment by Exeu** [comment]
This is no issue regarding this library. To keep theissue system clean i will close this issue and would like you to ask this question on a place which is made for this (e.g. http://stackoverflow.com/).
Comments still can be added at any time to this question.
