### ISSUE TITLE
Installation & Use without composer possible?

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#82]
Is it possible to install and use this library without composer? In fact I want to integrate this into a plugin and the old fashion way with an include/require would be best in my opinion.

Thought about something like:
```php
require_once "lib/ApaiIO/ApaiIO.php";

use ApaiIO\Configuration\GenericConfiguration;
use ApaiIO\ApaiIO;

$conf = new GenericConfiguration();

$conf
    ->setCountry('com')
    ->setAccessKey('YOUR ACCESS KEY')
    ->setSecretKey('YOUR SECRET KEY')
    ->setAssociateTag('YOUR ASSOCIATE TAG');

$apaiIo = new ApaiIO($conf);
```

**Comment by kusflo** [comment]
I agree, can we use it without composer?

**Comment by Exeu** [comment]
Why it should not be possible?
Just include every singe file and you're done ;)

**Comment by flowdee** [comment]
Every single file? Isn't there a kind of loader file which can be included instead? would make sense and help a lot of ppl in my opinion.

**Comment by Exeu** [comment]
Yep but this file will not be included in this library. I'm sorry but you need to write such kind of file by yourself or using some more intelligent autload mechanisms instead.

Please have also a look here: http://php.net/manual/de/language.oop5.autoload.php
And of course (since the lib is PSR-Compliant) to http://www.php-fig.org/psr/psr-0/ and  https://gist.github.com/jwage/221634

**Comment by flowdee** [comment]
Why you don't want to share such a helpful file?

**Comment by Exeu** [comment]
I don't have such kind of file. Please see the links. There is ANY information you need to build this "file".

**Comment by Flaschenzug** [comment]
Hey there,

I tried to create an autoloader.php ... but without success.
What am I doing wrong ? Thanks for your help.

<?php

require 'lib/ApaiIO/ApaiIO.php';
require 'lib/ApaiIO/Common/OperationTrait.php';
require 'lib/ApaiIO/Configuration/ConfigurationInterface.php';
require 'lib/ApaiIO/Configuration/Country.php';
require 'lib/ApaiIO/Configuration/GenericConfiguration.php';
require 'lib/ApaiIO/Operations/AbstractOperation.php';
require 'lib/ApaiIO/Operations/BrowseNodeLookup.php';
require 'lib/ApaiIO/Operations/CartAdd.php';
require 'lib/ApaiIO/Operations/CartClear.php';
require 'lib/ApaiIO/Operations/CartCreate.php';
require 'lib/ApaiIO/Operations/Lookup.php';
require 'lib/ApaiIO/Operations/OperationInterface.php';
require 'lib/ApaiIO/Operations/Search.php';
require 'lib/ApaiIO/Operations/SimilarityLookup.php';
require 'lib/ApaiIO/Request/RequestFactory.php';
require 'lib/ApaiIO/Request/RequestInterface.php';
require 'lib/ApaiIO/Request/Rest/Request.php';
require 'lib/ApaiIO/Request/Soap/Request.php';
require 'lib/ApaiIO/Request/Util.php';
require 'lib/ApaiIO/ResponseTransformer/ObjectToArray.php';
require 'lib/ApaiIO/ResponseTransformer/ResponseTransformerFactory.php';
require 'lib/ApaiIO/ResponseTransformer/ResponseTransformerInterface.php';
require 'lib/ApaiIO/ResponseTransformer/XmlToDomDocument.php';
require 'lib/ApaiIO/ResponseTransformer/XmlToSimpleXmlObject.php';
require 'lib/ApaiIO/ResponseTransformer/Xslt.php';
