### ISSUE TITLE
How to limit the search results?

### ISSUE THREAD

**Issue by kingkarki** [Exeu/apai-io#83]
When i search some products here in demo http://apaiio.dev.pixel-web.org/ i get few results. But when i search in my app with same library i get many results. How can i limit the results?

it would be very helpful if you will put this http://apaiio.dev.pixel-web.org/ in git. Thanks

**Comment by kingkarki** [comment]
you closed the issue without replying

**Comment by Exeu** [comment]
This is no issue regarding this library. To keep the issue system clean i will close this "issue" and would like you to ask this question on a place which is made for this (e.g. http://stackoverflow.com/).
Comments still can be added at any time to this question.
