### ISSUE TITLE
Shipping costs

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#86]
Any suggestion how to receive the shipping costs of a product? Can't get the values so far

**Comment by Exeu** [comment]
http://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_response_elements.html

Can't see shipping costs here. So no its not possible.

**Comment by Exeu** [comment]
Maybe have a look: Totals
With luck you can somehow extract the value there..

**Comment by flowdee** [comment]
Thanks for the hint! I'm gonna take a look into the totals. Would be amazing if this works

**Comment by daFish** [comment]
There is also the [Amazon Marketplace Web Service](https://developer.amazonservices.com/index.html/185-4772162-7621621). Maybe you'll get the shipping information from there. I haven't used it nor did I checked the documentation, though.
