### ISSUE TITLE
Receiving multiplte countries

### ISSUE THREAD

**Issue by flowdee** [Exeu/apai-io#87]
Receiving the data for one country (e.g. Amazon.de) will work with the following example. So far so good.

```
try {
    $conf
        ->setCountry('de')
        ->setAccessKey(AWS_API_KEY)
        ->setSecretKey(AWS_API_SECRET_KEY)
        ->setAssociateTag(AWS_ASSOCIATE_TAG);
} catch (\Exception $e) {
    echo $e->getMessage();
}
$apaiIO = new ApaiIO($conf);
$search = new Search();
$search->setCategory('DVD');
$search->setActor('Bruce Willis');
$search->setKeywords('Stirb Langsam');
$search->setPage(3);
$search->setResponseGroup(array('Large', 'Small'));
$formattedResponse = $apaiIO->runOperation($search);
echo $formattedResponse;
```

Is there a chance to get multiple country responses (e.g. for Amazon.com, Amazon.de & Amazon.es) within one api call? So in fact that I got the product links for each country store?

**Comment by daFish** [comment]
I guess this is not possible. You need to set the associate tag for each country separately. However, as the tag is identical for each european country, the API must support it and this is not the case.
