### ISSUE TITLE
Class 'ApaiIO\Configuration\GenericConfiguration' not found Error!

### ISSUE THREAD

**Issue by macpatel** [Exeu/apai-io#88]
Hi guyz,

I have installed apai-io using composer in Laravel 5.

But when i try to run the below code. It give me error.

"Class 'ApaiIO\Configuration\GenericConfiguration' not found Error!"

AmazonAPI.php- 
```php
<?php

use ApaiIO\ApaiIO;
use ApaiIO\Configuration\GenericConfiguration;
use ApaiIO\Operations\Lookup;

$conf = new GenericConfiguration();
?>
```

**Comment by 3even** [comment]
Same issue here.

**Comment by dirk-helbert** [comment]
Try 

`require_once dirname(__FILE__). '/vendor/autoload.php';`

and type in console

`composer dumpautoload`
