### ISSUE TITLE
Installing dependencies using composer failed

### ISSUE THREAD

**Issue by Bhabatosh** [Exeu/apai-io#89]
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package exeu/apai-io 1.0.0 could not be found.
Problem 2
- Installation request for exeu/apai-io dev-master -> satisfiable by exeu/apai-io[dev-master].
- exeu/apai-io dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.

Potential causes:

    A typo in the package name
    The package is not available in a stable-enough version according to your minimum-stability setting see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

my composer.json file content as follows:
{
"name": "exeu/apai-io",
"type": "library",
"description": "Amazon Product Advertising PHP Library",
"keywords": ["Amazon", "ECS", "Product Advertising", "SOAP", "REST", "Products"],
"homepage": "https://github.com/Exeu/apai-io",
"license": "Apache-2.0",
"authors": [
{
"name": "Jan Eichhorn",
"email": "exeu65@googlemail.com",
"role": "Maintainer"
},
{
"name": "Dejan Spasic",
"email": "dejan.spasic@bitweise.biz",
"role": "Developer"
}
],
"support": {
"issues": "https://github.com/Exeu/apai-io/issues"
},
"minimum-stability": "dev",
"require": {
"php": ">=5.3.0",
"ext-curl": "*"
},
"require": {
"exeu/apai-io": "dev-master"
},
"autoload": {
"psr-0": { "ApaiIO": "lib/" }
}
}

**Comment by daFish** [comment]
You've posted the content of this repositories `composer.json`. You'll need to post the one you are using in your project.
