### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by MartinStehle** [Exeu/apai-io#96]
Hi, I tried to run apai-io on a WAMP system (thank to XAMPP). For me the installation seems to be written for Linux/Unix systems only. How to install apai-io on Windows?

**Comment by Exeu** [comment]
This is no issue regarding this library. To keep the issue system clean i will close this "issue" and would like you to ask this question on a place which is made for this (e.g. http://stackoverflow.com/).
Comments still can be added at any time to this question.

**Comment by MartinStehle** [comment]
Thank you for your note. I published my question here: http://stackoverflow.com/questions/34512546/how-to-install-apai-io-amazon-product-api-library-on-windows
