### ISSUE TITLE
create products ?

### ISSUE THREAD

**Issue by michabbb** [Exeu/apai-io#97]
hi there,

i am confused, as always when searching for amazon infos: should be there any functions for creating a   product ??

**Comment by Nisthar** [comment]
Is this package uptodate? I am getting <br />
<b>Fatal error</b>:  Uncaught exception 'RuntimeException' with message 'An error occurred while sending request. Error number: 6; Error message: Could not resolve host: webservices.amazon.com' in E:\wamp\www\amz\vendor\exeu\apai-io\lib\ApaiIO\Request\Rest\Request.php:172

**Comment by roman-1983** [comment]
Yes, it is update - seems to be a temporary error on your side. I can reach webservices.amazon.com.

**Comment by michabbb** [comment]
@Nisthar @roman-1983 
what have your posts todo with my question ? and why is "my" issue closed here ?

**Comment by roman-1983** [comment]
@michabbb it seems you do not have understand this package. It is not for requesting the merchants api but the amazon product advertising api. You can't create a product on amazon side. You only can query for product informations from amazon.

**Comment by michabbb** [comment]
@roman-1983 i just wanted this confirmed, thanks ! ;)
